version: "3.8"
services:
  browser:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./ssl:/ssl
    env_file:
      - .env
    environment:
      ENABLE_TLS: "true"
      TLS_CERT_PATH: "/ssl/cert.pem"
      TLS_KEY_PATH: "/ssl/key.pem"
